import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { cn } from '@/lib/utils'
import { Open_Sans } from 'next/font/google'
import { ModalProvider } from '@/components/providers/modal-provider'
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const font = Open_Sans({ subsets: ['latin']})

export const metadata: Metadata = {
  title: 'GAVDAGS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en"
      suppressHydrationWarning>
        <body className={cn(
          font.className,
          "bg-white -[#EADDC7] dark:bg-[#313338]",
        )}>
          <ThemeProvider attribute={'class'} defaultTheme="dark" enableSystem storageKey='gavdags-theme'>
            <ModalProvider />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}