name: CSS Testing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - test2

jobs:
  lint_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Change to front_end directory
        run: cd front_end

      - name: Install dependencies
        run: npm install
        working-directory: front_end

      - name: Run Stylelint with auto-fixing
        run: npx stylelint "**/*.css" --fix
        working-directory: front_end