name: React CI

on:
  push:
    branches:
    - '*'
  pull_request:
    branches: [ main, test2 ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: npm install
      working-directory: front_end

    - name: Lint
      run: npm run lint
      working-directory: ./front_end

    # - name: Build
    #   run: npm run build
    #   working-directory: front_end
    - name: Preview build
      run: npm run build
      working-directory: front_end

    - name: Run tests
      run: npm run test
      working-directory: front_end

