name: React and CSS Tests

on:
  push:
    branches:
      - '*'           
  pull_request:
    branches:
      - main         

jobs:
  react-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: front_end

      - name: Run React unit tests (Jest)
        run: npm test -- --ci --coverage
        working-directory: front_end

      - name: Run ESLint
        run: npm run lint
        working-directory: front_end

      - name: Run Stylelint (CSS/SCSS)
        run: npx stylelint "**/*.{css,scss}" --allow-empty-input
        working-directory: front_end

